line-length = 88
target-version = "py312"

builtins = ["spark", "dbutils", "display", "displayHTML"]

extend-exclude = ["*.ipynb"]

[lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
